function [As, Ad, Omega, IalphaAsvestas, timeinfo] = qol_rrq_mex(m, tx, n, sx, snx, sw, rts, rps, order, nquad, orderff, distff, exterior, isimd, ichart, sxbd_chart, rv_chart, tgl, wgl, Dgl, w_bclag, Legmat, umatr, vmatr, As, Ad, Omega, IalphaAsvestas, timeinfo)
m       = double(m);
n       = double(n);
order   = double(order);
nquad   = double(nquad);
orderff = double(orderff);
isimd   = double(isimd);
distff  = double(distff);
exterior = double(logical(exterior));
tx  = double(reshape(tx,  3, m));
sx  = double(reshape(sx,  3, n));
snx = double(reshape(snx, 3, n));
rts = double(reshape(rts, 3, n));
rps = double(reshape(rps, 3, n));
sw  = double(sw(:));
h_dim = order*(order+1)/2;
if nargin < 25 || isempty(As), As = zeros(m, n); end
if nargin < 26 || isempty(Ad), Ad = zeros(m, n); end
if nargin < 27 || isempty(Omega), Omega = zeros(4*h_dim, m); end
if nargin < 28 || isempty(IalphaAsvestas), IalphaAsvestas = zeros(m, 1); end
if nargin < 29 || isempty(timeinfo), timeinfo = zeros(20, 1); end
nbd = 3*nquad;
ichart = double(ichart);
sxbd_chart = double(reshape(sxbd_chart, 3, nbd));
rv_chart   = double(reshape(rv_chart, 3, 3));
tgl = double(reshape(tgl, nquad, 1));
wgl = double(reshape(wgl, nquad, 1));
Dgl = double(reshape(Dgl, nquad, nquad));
w_bclag = double(reshape(w_bclag, nquad, 1));
Legmat = double(reshape(Legmat, nquad, nquad));
umatr = double(reshape(umatr, h_dim, h_dim));
vmatr = double(reshape(vmatr, h_dim, h_dim));
mh = 4*h_dim;
mex_id_ = 'qol_rrq_mex(c i int64_t[x], c i double[xx], c i int64_t[x], c i double[xx], c i double[xx], c i double[x], c i double[xx], c i double[xx], c i int64_t[x], c i int64_t[x], c i int64_t[x], c i double[x], c i int64_t[x], c i int64_t[x], c i int64_t[x], c i double[xx], c i double[xx], c i double[x], c i double[x], c i double[xx], c i double[x], c i double[xx], c i double[xx], c i double[xx], c io double[xx], c io double[xx], c io double[xx], c io double[x], c io double[x])';
[As, Ad, Omega, IalphaAsvestas, timeinfo] = qotential_mex(mex_id_, m, tx, n, sx, snx, sw, rts, rps, order, nquad, orderff, distff, exterior, isimd, ichart, sxbd_chart, rv_chart, tgl, wgl, Dgl, w_bclag, Legmat, umatr, vmatr, As, Ad, Omega, IalphaAsvestas, timeinfo, 1, 3, m, 1, 3, n, 3, n, n, 3, n, 3, n, 1, 1, 1, 1, 1, 1, 1, 3, nbd, 3, 3, nquad, nquad, nquad, nquad, nquad, nquad, nquad, h_dim, h_dim, h_dim, h_dim, m, n, m, n, mh, m, m, 20);
end
