function [R, c, sxbd, swbd, stangbd, sspbd, qhat, Fbd, Fxbd, Fybd, Fzbd, Mmatrix] = qol_build_closepanel_precomp_mex(n, sx, snx, sw, r_vert, nterms, h_dim, nbd, sbdnp, nquad, alpha, exterior, ichart, sxbd_chart, tgl, wgl, Dgl, umatr, R, c, sxbd, swbd, stangbd, sspbd, qhat, Fbd, Fxbd, Fybd, Fzbd, Mmatrix)
n = double(n);
nterms = double(nterms);
h_dim = double(h_dim);
nbd = double(nbd);
sbdnp = double(sbdnp);
nquad = double(nquad);
alpha = double(alpha);
exterior = double(logical(exterior));
ichart = double(ichart);
sx = double(reshape(sx, 3, n));
snx = double(reshape(snx, 3, n));
sw = double(sw(:));
r_vert = double(reshape(r_vert, 3, 3));
sxbd_chart = double(reshape(sxbd_chart, 3, nbd));
nsq = (nterms+1)^2;
mh = 4*h_dim;
tgl = double(reshape(tgl, nquad, 1));
wgl = double(reshape(wgl, nquad, 1));
Dgl = double(reshape(Dgl, nquad, nquad));
umatr = double(reshape(umatr, h_dim, h_dim));
if nargin < 19 || isempty(R), R = zeros(3, 3); end
if nargin < 20 || isempty(c), c = zeros(3, 1); end
if nargin < 21 || isempty(sxbd), sxbd = zeros(3, nbd); end
if nargin < 22 || isempty(swbd), swbd = zeros(nbd, 1); end
if nargin < 23 || isempty(stangbd), stangbd = zeros(3, nbd); end
if nargin < 24 || isempty(sspbd), sspbd = zeros(nbd, 1); end
if nargin < 25 || isempty(qhat), qhat = zeros(3, 1); end
if nargin < 26 || isempty(Fbd), Fbd = complex(zeros(nbd, nsq)); end
if nargin < 27 || isempty(Fxbd), Fxbd = complex(zeros(nbd, nsq)); end
if nargin < 28 || isempty(Fybd), Fybd = complex(zeros(nbd, nsq)); end
if nargin < 29 || isempty(Fzbd), Fzbd = complex(zeros(nbd, nsq)); end
if nargin < 30 || isempty(Mmatrix), Mmatrix = zeros(mh, mh); end
mex_id_ = 'qol_build_closepanel_precomp_mex(c i int64_t[x], c i double[xx], c i double[xx], c i double[x], c i double[xx], c i int64_t[x], c i int64_t[x], c i int64_t[x], c i int64_t[x], c i int64_t[x], c i double[x], c i int64_t[x], c i int64_t[x], c i double[xx], c i double[x], c i double[x], c i double[xx], c i double[xx], c io double[xx], c io double[x], c io double[xx], c io double[x], c io double[xx], c io double[x], c io double[x], c io dcomplex[xx], c io dcomplex[xx], c io dcomplex[xx], c io dcomplex[xx], c io double[xx])';
[R, c, sxbd, swbd, stangbd, sspbd, qhat, Fbd, Fxbd, Fybd, Fzbd, Mmatrix] = qotential_mex(mex_id_, n, sx, snx, sw, r_vert, nterms, h_dim, nbd, sbdnp, nquad, alpha, exterior, ichart, sxbd_chart, tgl, wgl, Dgl, umatr, R, c, sxbd, swbd, stangbd, sspbd, qhat, Fbd, Fxbd, Fybd, Fzbd, Mmatrix, 1, 3, n, 3, n, n, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 3, nbd, nquad, nquad, nquad, nquad, h_dim, h_dim, 3, 3, 3, 3, nbd, nbd, 3, nbd, nbd, 3, nbd, nsq, nbd, nsq, nbd, nsq, nbd, nsq, mh, mh);
end
